ALTER TYPE public.region ADD VALUE IF NOT EXISTS 'SLTR';
ALTER TYPE public.region ADD VALUE IF NOT EXISTS 'CTR';
ALTER TYPE public.region ADD VALUE IF NOT EXISTS 'GTR';
ALTER TYPE public.region ADD VALUE IF NOT EXISTS 'LTR';